// @bind-standard /sdk
// TypeScript SDK for the BIND Standard — types, interfaces, and terminology client.

export type {
  CodeSystem,
  CodeSystemConcept,
  CodeSystemSummary,
  Designation,
  LookupResult,
  TerminologyClientOptions,
  TerminologyError,
} from "./terminology/index";
// --- Terminology Server Types & Client ---
export {
  TerminologyClient,
  TerminologyClientError,
} from "./terminology/index";
// --- BIND Standard Types ---
export type {
  AdditionalInterest,
  // Base types
  Address,
  AssetValuation,
  Attachment,
  // Primitives
  BindBase64Binary,
  BindBoolean,
  BindDate,
  BindDateTime,
  BindDecimal,
  BindId,
  BindInstant,
  BindInteger,
  BindMarkdown,
  BindPercentage,
  BindPositiveInt,
  BindString,
  BindTime,
  BindUri,
  BindUrl,
  BindYear,
  CarrierAppointment,
  Certificate,
  CertificateHolder,
  Claim,
  Claimant,
  ClaimFinancials,
  ClaimPayment,
  ClaimReport,
  ClaimsAssignment,
  Classification,
  CodeableConcept,
  Coding,
  Commission,
  CommissionSplit,
  CommissionTier,
  ContactPoint,
  Coverage,
  CoverageExtension,
  CoverageLimit,
  CoverageSummary,
  // Complex data types
  DateTimePeriod,
  Deductible,
  DrivingViolation,
  Endorsement,
  EndorsementChange,
  Exclusion,
  FinancialRating,
  GeoPoint,
  GeoRegion,
  HumanName,
  Identifier,
  InsuranceForm,
  InsuranceSpecialty,
  // Insurance-specific data types
  InsuranceUnit,
  Insured,
  LargeLoss,
  License,
  Lienholder,
  Location,
  LossHistory,
  Meta,
  Money,
  MoneyWithConversion,
  MultiCurrencyMoney,
  NamedDriver,
  Note,
  Organization,
  Period,
  Person,
  PersonRole,
  Policy,
  PolicyCondition,
  PolicyTransaction,
  // Supporting types
  Premium,
  PremiumAdjustment,
  PremiumAllocation,
  PremiumBasis,
  PremiumInstallment,
  PremiumLineItem,
  Quantity,
  QuestionResponse,
  Quote,
  Reference,
  Resource,
  Risk,
  RiskCharacteristic,
  ScheduledItem,
  SplitLimitComponent,
  SprinklerDetail,
  Subjectivity,
  // Resources
  Submission,
  SubrogationDetail,
  UcumUnit,
} from "./types/index";
export { BIND_INSURANCE_UNITS_SYSTEM, UCUM_SYSTEM } from "./types/index";
